title: TARA (Turbulent Astroplasma Replicator Accessories)
logo: /assets/img/logo.png
description: Turbulent Astroplasma Replicator Accessories
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
